# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IM8z_iIqal6QqAOpIGnw59Zn2MkrEDji
"""

!wget -O /content/caltech-101.zip "https://data.caltech.edu/records/mzrjq-6wc02/files/caltech-101.zip?download=1"

!mkdir -p /content/caltech101
!unzip -q /content/caltech-101.zip -d /content/caltech101

import os

print("Contents of /content:")
print(os.listdir("/content"))

print("\nContents of /content/caltech101:")
print(os.listdir("/content/caltech101"))

import os

print(os.listdir("/content/caltech101/caltech-101"))

!mkdir -p /content/caltech101/dataset
!tar -xzf /content/caltech101/caltech-101/101_ObjectCategories.tar.gz \
    -C /content/caltech101/dataset

import os

print(os.listdir("/content/caltech101/dataset"))

import os

for root, dirs, files in os.walk("/content"):
    if "101_ObjectCategories" in dirs:
        print(os.path.join(root, "101_ObjectCategories"))

import os
import numpy as np
import matplotlib.pyplot as plt
import plotly.graph_objects as go

from PIL import Image
from skimage.feature import hog

from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import accuracy_score
from sklearn.decomposition import PCA

path = "/content/caltech101/dataset/101_ObjectCategories"

images = []
features = []
hog_images = []
labels = []

print("\n======================================")
print("LOADING DATASET")
print("======================================")

for class_name in sorted(os.listdir(path)):

    class_path = os.path.join(
        path,
        class_name
    )

    if not os.path.isdir(class_path):
        continue

    if class_name == "BACKGROUND_Google":
        continue

    print(
        "Processing class:",
        class_name
    )

    for file_name in os.listdir(class_path):

        file_path = os.path.join(
            class_path,
            file_name
        )

        with Image.open(file_path) as img:

            image = img.convert("L")

            image = image.resize(
                (64, 64)
            )

            image = np.array(image)


        feature, hogimage = hog(
            image,
            orientations=9,
            pixels_per_cell=(8, 8),
            cells_per_block=(2, 2),
            block_norm="L2-Hys",
            visualize=True
        )


        images.append(image)
        features.append(feature)
        hog_images.append(hogimage)
        labels.append(class_name)


images = np.array(images)
features = np.array(features)
hog_images = np.array(hog_images)
labels = np.array(labels)

print("Images shape:")
print(images.shape)

print("\nHOG features shape:")
print(features.shape)

print("\nHOG images shape:")
print(hog_images.shape)

print("\nLabels shape:")
print(labels.shape)

print("\nNumber of classes:")
print(len(np.unique(labels)))

print("\nNumber of images:")
print(len(images))


X = features
y = labels


X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)



print("Training samples:")
print(X_train.shape)

print("Testing samples:")
print(X_test.shape)


scaler = StandardScaler()


X_train_scaled = scaler.fit_transform(
    X_train
)

X_test_scaled = scaler.transform(
    X_test
)


print("Mean:")
print(X_train_scaled.mean())

print("Std:")
print(X_train_scaled.std())


model = SVC()


param_grid = {
    "C": [
        0.01,
        0.1,
        1
    ],

    "gamma": [
        "scale",
        0.01,
        0.1
    ],

    "kernel": [
        "linear",
        "rbf"
    ]
}


grid_model = GridSearchCV(
    estimator=model,
    param_grid=param_grid,
    cv=3,
    n_jobs=-1,
    verbose=1,
    scoring="accuracy"
)


print("\n======================================")
print("TRAINING SVM")
print("======================================")


grid_model.fit(
    X_train_scaled,
    y_train
)


best_model = grid_model.best_estimator_

print("Best parameters:")
print(
    grid_model.best_params_
)

print("\nBest CV Accuracy:")
print(
    grid_model.best_score_
)


print("\nBest model:")
print(
    best_model
)


predictions = best_model.predict(
    X_test_scaled
)


accuracy = accuracy_score(
    y_test,
    predictions
)


print("Test Accuracy:")
print(
    accuracy
)


print("\nNumber of support vectors:")
print(
    len(
        best_model.support_vectors_
    )
)


number_to_show = min(
    6,
    len(images)
)


plt.figure(
    figsize=(10, 15)
)


for k in range(
    number_to_show
):

    plt.subplot(
        number_to_show,
        2,
        2 * k + 1
    )

    plt.imshow(
        images[k],
        cmap="gray"
    )

    plt.title(
        "Original - " +
        labels[k]
    )

    plt.axis("off")


    plt.subplot(
        number_to_show,
        2,
        2 * k + 2
    )

    plt.imshow(
        hog_images[k],
        cmap="gray"
    )

    plt.title(
        "HOG"
    )

    plt.axis("off")


plt.tight_layout()

plt.show()


pca = PCA(
    n_components=3
)


X_pca = pca.fit_transform(
    X_train_scaled
)


print("Original feature dimension:")
print(
    X_train_scaled.shape[1]
)


print("\nPCA shape:")
print(
    X_pca.shape
)


print("\nExplained variance ratio:")
print(
    pca.explained_variance_ratio_
)


print("\nTotal explained variance:")
print(
    pca.explained_variance_ratio_.sum()
)


classes = np.unique(
    y
)


class_to_number = {
    class_name: number
    for number, class_name
    in enumerate(classes)
}


numeric_y = np.array([
    class_to_number[class_name]
    for class_name in y_train
])


print("\nNumber of classes:")
print(
    len(classes)
)


x_min = (
    X_pca[:, 0].min()
    - 1
)

x_max = (
    X_pca[:, 0].max()
    + 1
)


y_min = (
    X_pca[:, 1].min()
    - 1
)

y_max = (
    X_pca[:, 1].max()
    + 1
)


z_min = (
    X_pca[:, 2].min()
    - 1
)

z_max = (
    X_pca[:, 2].max()
    + 1
)


grid_size = 15


xx, yy, zz = np.meshgrid(

    np.linspace(
        x_min,
        x_max,
        grid_size
    ),

    np.linspace(
        y_min,
        y_max,
        grid_size
    ),

    np.linspace(
        z_min,
        z_max,
        grid_size
    ),

    indexing="ij"
)


grid_pca = np.c_[
    xx.ravel(),
    yy.ravel(),
    zz.ravel()
]


print("\nNumber of 3D grid points:")
print(
    grid_pca.shape[0]
)


grid_hog = pca.inverse_transform(
    grid_pca
)


print("\nGrid in original HOG space:")
print(
    grid_hog.shape
)


print(
    "\nPredicting 3D grid using SVM..."
)


grid_predictions = best_model.predict(
    grid_hog
)


print(
    "Prediction completed."
)


numeric_predictions = np.array([

    class_to_number[
        class_name
    ]

    for class_name
    in grid_predictions

])


numeric_predictions = (
    numeric_predictions.reshape(
        xx.shape
    )
)


fig = go.Figure()


fig.add_trace(
    go.Scatter3d(

        x=X_pca[:, 0],

        y=X_pca[:, 1],

        z=X_pca[:, 2],

        mode="markers",

        marker=dict(

            size=3,

            color=numeric_y,

            colorscale="Viridis",

            opacity=0.75,

            colorbar=dict(
                title="Class"
            )
        ),

        text=y_train,

        hovertemplate=(

            "Class: %{text}<br>"

            "PCA-1: %{x:.2f}<br>"

            "PCA-2: %{y:.2f}<br>"

            "PCA-3: %{z:.2f}"

            "<extra></extra>"
        ),

        name="Training Samples"
    )
)


fig.add_trace(
    go.Scatter3d(

        x=xx.ravel(),

        y=yy.ravel(),

        z=zz.ravel(),

        mode="markers",

        marker=dict(

            size=2,

            color=numeric_predictions.ravel(),

            colorscale="Viridis",

            opacity=0.05
        ),

        hoverinfo="skip",

        name="SVM Decision Regions",

        showlegend=True
    )
)


fig.update_layout(

    title=(
        "3D SVM Classification - "
        "Caltech101"
    ),

    scene=dict(

        xaxis_title="PCA Component 1",

        yaxis_title="PCA Component 2",

        zaxis_title="PCA Component 3"
    ),

    width=1200,

    height=900,

    legend=dict(

        title="SVM Classification",

        itemsizing="constant"
    )
)


fig.show()